"""initial_schema

Revision ID: d29988510650
Revises: 
Create Date: 2026-05-28 15:17:06.718557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd29988510650'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('worker', 'director', name='userrole'), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('director_code', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_director_code'), 'users', ['director_code'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('director_auto_planning_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('director_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('minute', sa.Integer(), nullable=False),
    sa.Column('auto_pulls_enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_save_mode', sa.String(length=16), nullable=False),
    sa.Column('pulls_limit', sa.Integer(), nullable=True),
    sa.Column('pulls_limits_by_site', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.Column('last_run_week_iso', sa.String(length=10), nullable=True),
    sa.Column('last_run_at', sa.BigInteger(), nullable=True),
    sa.Column('last_error', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['director_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('director_id', name='uq_director_auto_planning_director')
    )
    op.create_index(op.f('ix_director_auto_planning_configs_director_id'), 'director_auto_planning_configs', ['director_id'], unique=False)
    op.create_index(op.f('ix_director_auto_planning_configs_id'), 'director_auto_planning_configs', ['id'], unique=False)
    op.create_index(op.f('ix_director_auto_planning_configs_last_run_week_iso'), 'director_auto_planning_configs', ['last_run_week_iso'], unique=False)
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('director_id', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['director_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sites_deleted_at'), 'sites', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_sites_director_id'), 'sites', ['director_id'], unique=False)
    op.create_index(op.f('ix_sites_id'), 'sites', ['id'], unique=False)
    op.create_table('site_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('hours_per_week', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_assignments_id'), 'site_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_site_assignments_site_id'), 'site_assignments', ['site_id'], unique=False)
    op.create_index(op.f('ix_site_assignments_worker_id'), 'site_assignments', ['worker_id'], unique=False)
    op.create_table('site_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=10), nullable=False),
    sa.Column('text', sa.String(length=4000), nullable=False),
    sa.Column('created_week_iso', sa.String(length=10), nullable=False),
    sa.Column('stopped_week_iso', sa.String(length=10), nullable=True),
    sa.Column('origin_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_messages_created_week_iso'), 'site_messages', ['created_week_iso'], unique=False)
    op.create_index(op.f('ix_site_messages_id'), 'site_messages', ['id'], unique=False)
    op.create_index(op.f('ix_site_messages_origin_id'), 'site_messages', ['origin_id'], unique=False)
    op.create_index(op.f('ix_site_messages_scope'), 'site_messages', ['scope'], unique=False)
    op.create_index(op.f('ix_site_messages_site_id'), 'site_messages', ['site_id'], unique=False)
    op.create_index(op.f('ix_site_messages_stopped_week_iso'), 'site_messages', ['stopped_week_iso'], unique=False)
    op.create_table('site_week_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('week_iso', sa.String(length=10), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'week_iso', 'scope', name='uq_site_week_plans_site_week_scope')
    )
    op.create_index(op.f('ix_site_week_plans_id'), 'site_week_plans', ['id'], unique=False)
    op.create_index(op.f('ix_site_week_plans_scope'), 'site_week_plans', ['scope'], unique=False)
    op.create_index(op.f('ix_site_week_plans_site_id'), 'site_week_plans', ['site_id'], unique=False)
    op.create_index(op.f('ix_site_week_plans_week_iso'), 'site_week_plans', ['week_iso'], unique=False)
    op.create_table('site_weekly_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('week_iso', sa.String(length=10), nullable=False),
    sa.Column('availability', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'week_iso', name='uq_site_weekly_availability_site_week')
    )
    op.create_index(op.f('ix_site_weekly_availability_id'), 'site_weekly_availability', ['id'], unique=False)
    op.create_index(op.f('ix_site_weekly_availability_site_id'), 'site_weekly_availability', ['site_id'], unique=False)
    op.create_index(op.f('ix_site_weekly_availability_week_iso'), 'site_weekly_availability', ['week_iso'], unique=False)
    op.create_table('site_workers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('max_shifts', sa.Integer(), nullable=False),
    sa.Column('roles', sa.JSON(), nullable=False),
    sa.Column('availability', sa.JSON(), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('pending_approval', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('removed_from_week_iso', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'name', name='uq_site_workers_site_name')
    )
    op.create_index(op.f('ix_site_workers_id'), 'site_workers', ['id'], unique=False)
    op.create_index(op.f('ix_site_workers_phone'), 'site_workers', ['phone'], unique=False)
    op.create_index(op.f('ix_site_workers_removed_from_week_iso'), 'site_workers', ['removed_from_week_iso'], unique=False)
    op.create_index(op.f('ix_site_workers_site_id'), 'site_workers', ['site_id'], unique=False)
    op.create_index(op.f('ix_site_workers_user_id'), 'site_workers', ['user_id'], unique=False)
    op.create_table('worker_invite_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.String(length=64), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('director_id', sa.Integer(), nullable=False),
    sa.Column('used_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('expires_at', sa.BigInteger(), nullable=False),
    sa.Column('used_at', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['director_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['used_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_invite_tokens_director_id'), 'worker_invite_tokens', ['director_id'], unique=False)
    op.create_index(op.f('ix_worker_invite_tokens_expires_at'), 'worker_invite_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_worker_invite_tokens_id'), 'worker_invite_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_worker_invite_tokens_site_id'), 'worker_invite_tokens', ['site_id'], unique=False)
    op.create_index(op.f('ix_worker_invite_tokens_token_id'), 'worker_invite_tokens', ['token_id'], unique=True)
    op.create_index(op.f('ix_worker_invite_tokens_used_at'), 'worker_invite_tokens', ['used_at'], unique=False)
    op.create_index(op.f('ix_worker_invite_tokens_used_by_user_id'), 'worker_invite_tokens', ['used_by_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_worker_invite_tokens_used_by_user_id'), table_name='worker_invite_tokens')
    op.drop_index(op.f('ix_worker_invite_tokens_used_at'), table_name='worker_invite_tokens')
    op.drop_index(op.f('ix_worker_invite_tokens_token_id'), table_name='worker_invite_tokens')
    op.drop_index(op.f('ix_worker_invite_tokens_site_id'), table_name='worker_invite_tokens')
    op.drop_index(op.f('ix_worker_invite_tokens_id'), table_name='worker_invite_tokens')
    op.drop_index(op.f('ix_worker_invite_tokens_expires_at'), table_name='worker_invite_tokens')
    op.drop_index(op.f('ix_worker_invite_tokens_director_id'), table_name='worker_invite_tokens')
    op.drop_table('worker_invite_tokens')
    op.drop_index(op.f('ix_site_workers_user_id'), table_name='site_workers')
    op.drop_index(op.f('ix_site_workers_site_id'), table_name='site_workers')
    op.drop_index(op.f('ix_site_workers_removed_from_week_iso'), table_name='site_workers')
    op.drop_index(op.f('ix_site_workers_phone'), table_name='site_workers')
    op.drop_index(op.f('ix_site_workers_id'), table_name='site_workers')
    op.drop_table('site_workers')
    op.drop_index(op.f('ix_site_weekly_availability_week_iso'), table_name='site_weekly_availability')
    op.drop_index(op.f('ix_site_weekly_availability_site_id'), table_name='site_weekly_availability')
    op.drop_index(op.f('ix_site_weekly_availability_id'), table_name='site_weekly_availability')
    op.drop_table('site_weekly_availability')
    op.drop_index(op.f('ix_site_week_plans_week_iso'), table_name='site_week_plans')
    op.drop_index(op.f('ix_site_week_plans_site_id'), table_name='site_week_plans')
    op.drop_index(op.f('ix_site_week_plans_scope'), table_name='site_week_plans')
    op.drop_index(op.f('ix_site_week_plans_id'), table_name='site_week_plans')
    op.drop_table('site_week_plans')
    op.drop_index(op.f('ix_site_messages_stopped_week_iso'), table_name='site_messages')
    op.drop_index(op.f('ix_site_messages_site_id'), table_name='site_messages')
    op.drop_index(op.f('ix_site_messages_scope'), table_name='site_messages')
    op.drop_index(op.f('ix_site_messages_origin_id'), table_name='site_messages')
    op.drop_index(op.f('ix_site_messages_id'), table_name='site_messages')
    op.drop_index(op.f('ix_site_messages_created_week_iso'), table_name='site_messages')
    op.drop_table('site_messages')
    op.drop_index(op.f('ix_site_assignments_worker_id'), table_name='site_assignments')
    op.drop_index(op.f('ix_site_assignments_site_id'), table_name='site_assignments')
    op.drop_index(op.f('ix_site_assignments_id'), table_name='site_assignments')
    op.drop_table('site_assignments')
    op.drop_index(op.f('ix_sites_id'), table_name='sites')
    op.drop_index(op.f('ix_sites_director_id'), table_name='sites')
    op.drop_index(op.f('ix_sites_deleted_at'), table_name='sites')
    op.drop_table('sites')
    op.drop_index(op.f('ix_director_auto_planning_configs_last_run_week_iso'), table_name='director_auto_planning_configs')
    op.drop_index(op.f('ix_director_auto_planning_configs_id'), table_name='director_auto_planning_configs')
    op.drop_index(op.f('ix_director_auto_planning_configs_director_id'), table_name='director_auto_planning_configs')
    op.drop_table('director_auto_planning_configs')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_director_code'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
